"""6_check if any update

Revision ID: 12cd04aa5ea8
Revises: c18d603127eb
Create Date: 2022-07-25 17:47:06.276986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cd04aa5ea8'
down_revision = 'c18d603127eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
