"""Before online

Revision ID: 231c8c04fbba
Revises: 05f5a101740f
Create Date: 2022-03-29 20:42:10.010729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231c8c04fbba'
down_revision = '05f5a101740f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
