"""annual leaves as Integer_2

Revision ID: 46acb87f4e02
Revises: c53451dc62d9
Create Date: 2022-04-06 20:22:38.320590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46acb87f4e02'
down_revision = 'c53451dc62d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
