"""adjust and delete leave tables

Revision ID: 53b01be77570
Revises: 99b9352cc410
Create Date: 2022-04-20 22:47:31.536467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b01be77570'
down_revision = '99b9352cc410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
