"""add annual leaves

Revision ID: 5ef05da3daed
Revises: 231c8c04fbba
Create Date: 2022-04-06 20:07:44.497892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef05da3daed'
down_revision = '231c8c04fbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Annual_Leave', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Marital_Leave', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Maternity_Leave', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs_table', schema=None) as batch_op:
        batch_op.drop_column('Maternity_Leave')
        batch_op.drop_column('Marital_Leave')
        batch_op.drop_column('Annual_Leave')

    # ### end Alembic commands ###
