"""7_chinese version

Revision ID: 7411ca776f64
Revises: 12cd04aa5ea8
Create Date: 2023-04-08 10:45:37.264218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7411ca776f64'
down_revision = '12cd04aa5ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('公假', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('事假', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('病假', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('出差', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('補假', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('特休', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('喪假', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('月經假', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('婚假', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('產假', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('陪產假', sa.Float(), nullable=True))
        batch_op.drop_column('Menstruation_Leave')
        batch_op.drop_column('Marital_Leave')
        batch_op.drop_column('Sick_Leave')
        batch_op.drop_column('Personal_Leave')
        batch_op.drop_column('Paternity_Leave')
        batch_op.drop_column('Deferred_Leave')
        batch_op.drop_column('Funeral_Leave')
        batch_op.drop_column('Official_Leave')
        batch_op.drop_column('Annual_Leave')
        batch_op.drop_column('Business_Leave')
        batch_op.drop_column('Maternity_Leave')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Maternity_Leave', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Business_Leave', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Annual_Leave', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Official_Leave', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Funeral_Leave', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Deferred_Leave', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Paternity_Leave', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Personal_Leave', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Sick_Leave', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Marital_Leave', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Menstruation_Leave', sa.FLOAT(), nullable=True))
        batch_op.drop_column('陪產假')
        batch_op.drop_column('產假')
        batch_op.drop_column('婚假')
        batch_op.drop_column('月經假')
        batch_op.drop_column('喪假')
        batch_op.drop_column('特休')
        batch_op.drop_column('補假')
        batch_op.drop_column('出差')
        batch_op.drop_column('病假')
        batch_op.drop_column('事假')
        batch_op.drop_column('公假')

    # ### end Alembic commands ###
