"""revise leave_tables

Revision ID: 934aa8b3709a
Revises: b4d6bbb90f59
Create Date: 2022-04-08 00:24:03.674872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934aa8b3709a'
down_revision = 'b4d6bbb90f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
