"""revise some leave tables

Revision ID: 99b9352cc410
Revises: 934aa8b3709a
Create Date: 2022-04-12 19:45:15.664844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b9352cc410'
down_revision = '934aa8b3709a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
