"""1_test staff table

Revision ID: a6fe4926c47e
Revises: 65de66039a88
Create Date: 2022-07-14 10:55:12.674529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fe4926c47e'
down_revision = '65de66039a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
