"""add leave_tables

Revision ID: b4d6bbb90f59
Revises: ff7f4a181833
Create Date: 2022-04-06 20:46:28.412083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d6bbb90f59'
down_revision = 'ff7f4a181833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Annual_Leave_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_name'], ['staffs_table.staff_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Business_Leave_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_name'], ['staffs_table.staff_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Deffered_Leave_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_name'], ['staffs_table.staff_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Marital_Leave_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_name'], ['staffs_table.staff_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Maternity_Leave_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_name'], ['staffs_table.staff_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Personal_Leave_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_name'], ['staffs_table.staff_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sick_Leave_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_name'], ['staffs_table.staff_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sick_Leave_table')
    op.drop_table('Personal_Leave_table')
    op.drop_table('Maternity_Leave_table')
    op.drop_table('Marital_Leave_table')
    op.drop_table('Deffered_Leave_table')
    op.drop_table('Business_Leave_table')
    op.drop_table('Annual_Leave_table')
    # ### end Alembic commands ###
