"""5_add beacon col to staff_table

Revision ID: c18d603127eb
Revises: ecaa291a48e7
Create Date: 2022-07-25 15:03:54.303179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18d603127eb'
down_revision = 'ecaa291a48e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beacon', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs_table', schema=None) as batch_op:
        batch_op.drop_column('beacon')

    # ### end Alembic commands ###
