"""3_add revsed col to check

Revision ID: e2023adb2234
Revises: a6fe4926c47e
Create Date: 2022-07-19 16:14:17.886823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2023adb2234'
down_revision = 'a6fe4926c47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revised', sa.Boolean(), nullable=True))

    with op.batch_alter_table('checkout_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revised', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_table', schema=None) as batch_op:
        batch_op.drop_column('revised')

    with op.batch_alter_table('checkin_table', schema=None) as batch_op:
        batch_op.drop_column('revised')

    # ### end Alembic commands ###
